# Generated by Django 4.1.1 on 2022-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'متاح'), ('rental', 'مستأجر'), ('sold', 'تم البيع')], max_length=50, null=True),
        ),
    ]
