# Generated by Django 4.1.1 on 2022-09-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_book_photo_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo_book',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'availble'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
