# Generated by Django 5.0.1 on 2024-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_remove_book_photo_book_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='locations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_download',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_rental',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, default='/media/photo/photo1.png', null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
